# Generated by Django 4.2.11 on 2024-03-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("code", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateField()),
                ("end_at", models.DateField()),
                ("duration", models.CharField(max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=5)),
                ("count", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[("virtual", "Virtual"), ("central", "Central")],
                        max_length=10,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.program",
                    ),
                ),
            ],
        ),
    ]
